// Code generated by gogen. DO NOT EDIT.
package tutorial

import (
	"database/sql"
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ================ gormgen ================

type CustomerSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	Email     gsql.StringField[string]
	Phone     gsql.StringField[string]
	CreatedAt gsql.DateTimeField[time.Time]
	fieldType Customer
	alias     string
	tableName string
}

func (t CustomerSchemaType) TableName() string {
	return t.tableName
}

func (t CustomerSchemaType) Alias() string {
	return t.alias
}

func (t *CustomerSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.Phone = t.Phone.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t CustomerSchemaType) As(alias string) CustomerSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t CustomerSchemaType) ModelType() *Customer {
	return &t.fieldType
}

func (t CustomerSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t CustomerSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Email,
		t.Phone,
		t.CreatedAt,
	}
}

func (t CustomerSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var CustomerSchema = CustomerSchemaType{
	tableName: "customers",
	ID:        gsql.IntFieldOf[uint64]("customers", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Name:      gsql.StringFieldOf[string]("customers", "name"),
	Email:     gsql.StringFieldOf[string]("customers", "email"),
	Phone:     gsql.StringFieldOf[string]("customers", "phone"),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("customers", "created_at"),
	fieldType: Customer{},
}

type EmployeeSchemaType struct {
	ID         gsql.IntField[uint64]
	Name       gsql.StringField[string]
	Email      gsql.StringField[string]
	Department gsql.StringField[string]
	Salary     gsql.FloatField[float64]
	HireDate   gsql.DateTimeField[time.Time]
	BirthDate  gsql.DateTimeField[time.Time]
	IsActive   gsql.IntField[bool]
	fieldType  Employee
	alias      string
	tableName  string
}

func (t EmployeeSchemaType) TableName() string {
	return t.tableName
}

func (t EmployeeSchemaType) Alias() string {
	return t.alias
}

func (t *EmployeeSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.Department = t.Department.WithTable(&tn)
	t.Salary = t.Salary.WithTable(&tn)
	t.HireDate = t.HireDate.WithTable(&tn)
	t.BirthDate = t.BirthDate.WithTable(&tn)
	t.IsActive = t.IsActive.WithTable(&tn)
}

func (t EmployeeSchemaType) As(alias string) EmployeeSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t EmployeeSchemaType) ModelType() *Employee {
	return &t.fieldType
}

func (t EmployeeSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t EmployeeSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Email,
		t.Department,
		t.Salary,
		t.HireDate,
		t.BirthDate,
		t.IsActive,
	}
}

func (t EmployeeSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var EmployeeSchema = EmployeeSchemaType{
	tableName:  "employees",
	ID:         gsql.IntFieldOf[uint64]("employees", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Name:       gsql.StringFieldOf[string]("employees", "name"),
	Email:      gsql.StringFieldOf[string]("employees", "email", field.FlagUniqueIndex),
	Department: gsql.StringFieldOf[string]("employees", "department"),
	Salary:     gsql.FloatFieldOf[float64]("employees", "salary"),
	HireDate:   gsql.DateTimeFieldOf[time.Time]("employees", "hire_date"),
	BirthDate:  gsql.DateTimeFieldOf[time.Time]("employees", "birth_date"),
	IsActive:   gsql.IntFieldOf[bool]("employees", "is_active"),
	fieldType:  Employee{},
}

type OrderSchemaType struct {
	ID         gsql.IntField[uint64]
	CustomerID gsql.IntField[uint64]
	OrderDate  gsql.DateTimeField[time.Time]
	TotalPrice gsql.FloatField[float64]
	Status     gsql.StringField[string]
	fieldType  Order
	alias      string
	tableName  string
}

func (t OrderSchemaType) TableName() string {
	return t.tableName
}

func (t OrderSchemaType) Alias() string {
	return t.alias
}

func (t *OrderSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CustomerID = t.CustomerID.WithTable(&tn)
	t.OrderDate = t.OrderDate.WithTable(&tn)
	t.TotalPrice = t.TotalPrice.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
}

func (t OrderSchemaType) As(alias string) OrderSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrderSchemaType) ModelType() *Order {
	return &t.fieldType
}

func (t OrderSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrderSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CustomerID,
		t.OrderDate,
		t.TotalPrice,
		t.Status,
	}
}

func (t OrderSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrderSchema = OrderSchemaType{
	tableName:  "orders",
	ID:         gsql.IntFieldOf[uint64]("orders", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	CustomerID: gsql.IntFieldOf[uint64]("orders", "customer_id", field.FlagIndex),
	OrderDate:  gsql.DateTimeFieldOf[time.Time]("orders", "order_date"),
	TotalPrice: gsql.FloatFieldOf[float64]("orders", "total_price"),
	Status:     gsql.StringFieldOf[string]("orders", "status"),
	fieldType:  Order{},
}

type OrderItemSchemaType struct {
	ID        gsql.IntField[uint64]
	OrderID   gsql.IntField[uint64]
	ProductID gsql.IntField[uint64]
	Quantity  gsql.IntField[int]
	UnitPrice gsql.FloatField[float64]
	fieldType OrderItem
	alias     string
	tableName string
}

func (t OrderItemSchemaType) TableName() string {
	return t.tableName
}

func (t OrderItemSchemaType) Alias() string {
	return t.alias
}

func (t *OrderItemSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.OrderID = t.OrderID.WithTable(&tn)
	t.ProductID = t.ProductID.WithTable(&tn)
	t.Quantity = t.Quantity.WithTable(&tn)
	t.UnitPrice = t.UnitPrice.WithTable(&tn)
}

func (t OrderItemSchemaType) As(alias string) OrderItemSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrderItemSchemaType) ModelType() *OrderItem {
	return &t.fieldType
}

func (t OrderItemSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrderItemSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.OrderID,
		t.ProductID,
		t.Quantity,
		t.UnitPrice,
	}
}

func (t OrderItemSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrderItemSchema = OrderItemSchemaType{
	tableName: "order_items",
	ID:        gsql.IntFieldOf[uint64]("order_items", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	OrderID:   gsql.IntFieldOf[uint64]("order_items", "order_id", field.FlagIndex),
	ProductID: gsql.IntFieldOf[uint64]("order_items", "product_id", field.FlagIndex),
	Quantity:  gsql.IntFieldOf[int]("order_items", "quantity"),
	UnitPrice: gsql.FloatFieldOf[float64]("order_items", "unit_price"),
	fieldType: OrderItem{},
}

type OrgNodeSchemaType struct {
	ID        gsql.IntField[uint64]
	Name      gsql.StringField[string]
	ParentID  gsql.IntField[*uint64]
	Level     gsql.IntField[int]
	fieldType OrgNode
	alias     string
	tableName string
}

func (t OrgNodeSchemaType) TableName() string {
	return t.tableName
}

func (t OrgNodeSchemaType) Alias() string {
	return t.alias
}

func (t *OrgNodeSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.ParentID = t.ParentID.WithTable(&tn)
	t.Level = t.Level.WithTable(&tn)
}

func (t OrgNodeSchemaType) As(alias string) OrgNodeSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrgNodeSchemaType) ModelType() *OrgNode {
	return &t.fieldType
}

func (t OrgNodeSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrgNodeSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.ParentID,
		t.Level,
	}
}

func (t OrgNodeSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrgNodeSchema = OrgNodeSchemaType{
	tableName: "org_nodes",
	ID:        gsql.IntFieldOf[uint64]("org_nodes", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Name:      gsql.StringFieldOf[string]("org_nodes", "name"),
	ParentID:  gsql.IntFieldOf[*uint64]("org_nodes", "parent_id", field.FlagIndex),
	Level:     gsql.IntFieldOf[int]("org_nodes", "level"),
	fieldType: OrgNode{},
}

type ProductSchemaType struct {
	ID          gsql.IntField[uint64]
	Name        gsql.StringField[string]
	Category    gsql.StringField[string]
	Price       gsql.FloatField[float64]
	Stock       gsql.IntField[int]
	Description gsql.StringField[sql.NullString]
	CreatedAt   gsql.DateTimeField[time.Time]
	UpdatedAt   gsql.DateTimeField[time.Time]
	fieldType   Product
	alias       string
	tableName   string
}

func (t ProductSchemaType) TableName() string {
	return t.tableName
}

func (t ProductSchemaType) Alias() string {
	return t.alias
}

func (t *ProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Category = t.Category.WithTable(&tn)
	t.Price = t.Price.WithTable(&tn)
	t.Stock = t.Stock.WithTable(&tn)
	t.Description = t.Description.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
}

func (t ProductSchemaType) As(alias string) ProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t ProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Category,
		t.Price,
		t.Stock,
		t.Description,
		t.CreatedAt,
		t.UpdatedAt,
	}
}

func (t ProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProductSchema = ProductSchemaType{
	tableName:   "products",
	ID:          gsql.IntFieldOf[uint64]("products", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Name:        gsql.StringFieldOf[string]("products", "name"),
	Category:    gsql.StringFieldOf[string]("products", "category"),
	Price:       gsql.FloatFieldOf[float64]("products", "price"),
	Stock:       gsql.IntFieldOf[int]("products", "stock"),
	Description: gsql.StringFieldOf[sql.NullString]("products", "description"),
	CreatedAt:   gsql.DateTimeFieldOf[time.Time]("products", "created_at"),
	UpdatedAt:   gsql.DateTimeFieldOf[time.Time]("products", "updated_at"),
	fieldType:   Product{},
}

type SalesRecordSchemaType struct {
	ID          gsql.IntField[uint64]
	Region      gsql.StringField[string]
	Salesperson gsql.StringField[string]
	Amount      gsql.FloatField[float64]
	SaleDate    gsql.DateTimeField[time.Time]
	fieldType   SalesRecord
	alias       string
	tableName   string
}

func (t SalesRecordSchemaType) TableName() string {
	return t.tableName
}

func (t SalesRecordSchemaType) Alias() string {
	return t.alias
}

func (t *SalesRecordSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Region = t.Region.WithTable(&tn)
	t.Salesperson = t.Salesperson.WithTable(&tn)
	t.Amount = t.Amount.WithTable(&tn)
	t.SaleDate = t.SaleDate.WithTable(&tn)
}

func (t SalesRecordSchemaType) As(alias string) SalesRecordSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t SalesRecordSchemaType) ModelType() *SalesRecord {
	return &t.fieldType
}

func (t SalesRecordSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t SalesRecordSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Region,
		t.Salesperson,
		t.Amount,
		t.SaleDate,
	}
}

func (t SalesRecordSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var SalesRecordSchema = SalesRecordSchemaType{
	tableName:   "sales_records",
	ID:          gsql.IntFieldOf[uint64]("sales_records", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Region:      gsql.StringFieldOf[string]("sales_records", "region", field.FlagIndex),
	Salesperson: gsql.StringFieldOf[string]("sales_records", "salesperson"),
	Amount:      gsql.FloatFieldOf[float64]("sales_records", "amount"),
	SaleDate:    gsql.DateTimeFieldOf[time.Time]("sales_records", "sale_date", field.FlagIndex),
	fieldType:   SalesRecord{},
}

type TokenExchangeSchemaType struct {
	ID            gsql.IntField[uint64]
	Name          gsql.StringField[string]
	ExchangeRules gsql.StringField[string]
	fieldType     TokenExchange
	alias         string
	tableName     string
}

func (t TokenExchangeSchemaType) TableName() string {
	return t.tableName
}

func (t TokenExchangeSchemaType) Alias() string {
	return t.alias
}

func (t *TokenExchangeSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.ExchangeRules = t.ExchangeRules.WithTable(&tn)
}

func (t TokenExchangeSchemaType) As(alias string) TokenExchangeSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t TokenExchangeSchemaType) ModelType() *TokenExchange {
	return &t.fieldType
}

func (t TokenExchangeSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t TokenExchangeSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.ExchangeRules,
	}
}

func (t TokenExchangeSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var TokenExchangeSchema = TokenExchangeSchemaType{
	tableName:     "token_exchanges",
	ID:            gsql.IntFieldOf[uint64]("token_exchanges", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Name:          gsql.StringFieldOf[string]("token_exchanges", "name"),
	ExchangeRules: gsql.StringFieldOf[string]("token_exchanges", "exchange_rules"),
	fieldType:     TokenExchange{},
}

type TransactionSchemaType struct {
	ID        gsql.IntField[uint64]
	AccountID gsql.IntField[uint64]
	Amount    gsql.FloatField[float64]
	Type      gsql.StringField[string]
	CreatedAt gsql.DateTimeField[time.Time]
	fieldType Transaction
	alias     string
	tableName string
}

func (t TransactionSchemaType) TableName() string {
	return t.tableName
}

func (t TransactionSchemaType) Alias() string {
	return t.alias
}

func (t *TransactionSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.AccountID = t.AccountID.WithTable(&tn)
	t.Amount = t.Amount.WithTable(&tn)
	t.Type = t.Type.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t TransactionSchemaType) As(alias string) TransactionSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t TransactionSchemaType) ModelType() *Transaction {
	return &t.fieldType
}

func (t TransactionSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t TransactionSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.AccountID,
		t.Amount,
		t.Type,
		t.CreatedAt,
	}
}

func (t TransactionSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var TransactionSchema = TransactionSchemaType{
	tableName: "transactions",
	ID:        gsql.IntFieldOf[uint64]("transactions", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	AccountID: gsql.IntFieldOf[uint64]("transactions", "account_id", field.FlagIndex),
	Amount:    gsql.FloatFieldOf[float64]("transactions", "amount"),
	Type:      gsql.StringFieldOf[string]("transactions", "type"),
	CreatedAt: gsql.DateTimeFieldOf[time.Time]("transactions", "created_at"),
	fieldType: Transaction{},
}

type UserProfileSchemaType struct {
	ID        gsql.IntField[uint64]
	Username  gsql.StringField[string]
	Profile   gsql.StringField[string]
	fieldType UserProfile
	alias     string
	tableName string
}

func (t UserProfileSchemaType) TableName() string {
	return t.tableName
}

func (t UserProfileSchemaType) Alias() string {
	return t.alias
}

func (t *UserProfileSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Username = t.Username.WithTable(&tn)
	t.Profile = t.Profile.WithTable(&tn)
}

func (t UserProfileSchemaType) As(alias string) UserProfileSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserProfileSchemaType) ModelType() *UserProfile {
	return &t.fieldType
}

func (t UserProfileSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserProfileSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Username,
		t.Profile,
	}
}

func (t UserProfileSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserProfileSchema = UserProfileSchemaType{
	tableName: "user_profiles",
	ID:        gsql.IntFieldOf[uint64]("user_profiles", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	Username:  gsql.StringFieldOf[string]("user_profiles", "username"),
	Profile:   gsql.StringFieldOf[string]("user_profiles", "profile"),
	fieldType: UserProfile{},
}

type WorkflowJobSchemaType struct {
	ID         gsql.IntField[uint64]
	BusinessID gsql.IntField[uint64]
	RefType    gsql.StringField[string]
	Status     gsql.StringField[string]
	Step2      gsql.StringField[string]
	fieldType  WorkflowJob
	alias      string
	tableName  string
}

func (t WorkflowJobSchemaType) TableName() string {
	return t.tableName
}

func (t WorkflowJobSchemaType) Alias() string {
	return t.alias
}

func (t *WorkflowJobSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.BusinessID = t.BusinessID.WithTable(&tn)
	t.RefType = t.RefType.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
	t.Step2 = t.Step2.WithTable(&tn)
}

func (t WorkflowJobSchemaType) As(alias string) WorkflowJobSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t WorkflowJobSchemaType) ModelType() *WorkflowJob {
	return &t.fieldType
}

func (t WorkflowJobSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t WorkflowJobSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.BusinessID,
		t.RefType,
		t.Status,
		t.Step2,
	}
}

func (t WorkflowJobSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var WorkflowJobSchema = WorkflowJobSchemaType{
	tableName:  "workflow_jobs",
	ID:         gsql.IntFieldOf[uint64]("workflow_jobs", "id", field.FlagPrimaryKey|field.FlagAutoIncrement),
	BusinessID: gsql.IntFieldOf[uint64]("workflow_jobs", "business_id", field.FlagIndex),
	RefType:    gsql.StringFieldOf[string]("workflow_jobs", "ref_type"),
	Status:     gsql.StringFieldOf[string]("workflow_jobs", "status"),
	Step2:      gsql.StringFieldOf[string]("workflow_jobs", "step2"),
	fieldType:  WorkflowJob{},
}
