// Code generated by gormgen. DO NOT EDIT.
package tutorial

import (
	"database/sql"
	"time"

	gsql "github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
)

// ==================== Product Schema ====================

type ProductSchemaType struct {
	ID          field.IntExprField[uint64]
	Name        field.TextExprField[string]
	Category    field.TextExprField[string]
	Price       field.FloatExprField[float64]
	Stock       field.IntExprField[int]
	Description field.TextExprField[sql.NullString]
	CreatedAt   field.Comparable[time.Time]
	UpdatedAt   field.Comparable[time.Time]
	fieldType   Product
	alias       string
	tableName   string
}

func (t ProductSchemaType) TableName() string {
	return t.tableName
}

func (t ProductSchemaType) Alias() string {
	return t.alias
}

func (t *ProductSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Category = t.Category.WithTable(&tn)
	t.Price = t.Price.WithTable(&tn)
	t.Stock = t.Stock.WithTable(&tn)
	t.Description = t.Description.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
}

func (t ProductSchemaType) As(alias string) ProductSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ProductSchemaType) ModelType() *Product {
	return &t.fieldType
}

func (t ProductSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ProductSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Category,
		t.Price,
		t.Stock,
		t.Description,
		t.CreatedAt,
		t.UpdatedAt,
	}
}

func (t ProductSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ProductSchema = ProductSchemaType{
	tableName:   "products",
	ID:          field.NewIntExprField[uint64]("products", "id", field.FlagPrimaryKey),
	Name:        field.NewTextExprField[string]("products", "name"),
	Category:    field.NewTextExprField[string]("products", "category"),
	Price:       field.NewFloatExprField[float64]("products", "price"),
	Stock:       field.NewIntExprField[int]("products", "stock"),
	Description: field.NewTextExprField[sql.NullString]("products", "description"),
	CreatedAt:   field.NewComparable[time.Time]("products", "created_at"),
	UpdatedAt:   field.NewComparable[time.Time]("products", "updated_at"),
	fieldType:   Product{},
}

// ==================== Employee Schema ====================

type EmployeeSchemaType struct {
	ID         field.IntExprField[uint64]
	Name       field.TextExprField[string]
	Email      field.TextExprField[string]
	Department field.TextExprField[string]
	Salary     field.FloatExprField[float64]
	HireDate   field.Comparable[time.Time]
	BirthDate  field.Comparable[time.Time]
	IsActive   field.Comparable[bool]
	fieldType  Employee
	alias      string
	tableName  string
}

func (t EmployeeSchemaType) TableName() string {
	return t.tableName
}

func (t EmployeeSchemaType) Alias() string {
	return t.alias
}

func (t *EmployeeSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.Department = t.Department.WithTable(&tn)
	t.Salary = t.Salary.WithTable(&tn)
	t.HireDate = t.HireDate.WithTable(&tn)
	t.BirthDate = t.BirthDate.WithTable(&tn)
	t.IsActive = t.IsActive.WithTable(&tn)
}

func (t EmployeeSchemaType) As(alias string) EmployeeSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t EmployeeSchemaType) ModelType() *Employee {
	return &t.fieldType
}

func (t EmployeeSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t EmployeeSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Email,
		t.Department,
		t.Salary,
		t.HireDate,
		t.BirthDate,
		t.IsActive,
	}
}

func (t EmployeeSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var EmployeeSchema = EmployeeSchemaType{
	tableName:  "employees",
	ID:         field.NewIntExprField[uint64]("employees", "id", field.FlagPrimaryKey),
	Name:       field.NewTextExprField[string]("employees", "name"),
	Email:      field.NewTextExprField[string]("employees", "email", field.FlagIndex),
	Department: field.NewTextExprField[string]("employees", "department"),
	Salary:     field.NewFloatExprField[float64]("employees", "salary"),
	HireDate:   field.NewComparable[time.Time]("employees", "hire_date"),
	BirthDate:  field.NewComparable[time.Time]("employees", "birth_date"),
	IsActive:   field.NewComparable[bool]("employees", "is_active"),
	fieldType:  Employee{},
}

// ==================== Customer Schema ====================

type CustomerSchemaType struct {
	ID        field.IntExprField[uint64]
	Name      field.TextExprField[string]
	Email     field.TextExprField[string]
	Phone     field.TextExprField[string]
	CreatedAt field.Comparable[time.Time]
	fieldType Customer
	alias     string
	tableName string
}

func (t CustomerSchemaType) TableName() string {
	return t.tableName
}

func (t CustomerSchemaType) Alias() string {
	return t.alias
}

func (t *CustomerSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Email = t.Email.WithTable(&tn)
	t.Phone = t.Phone.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t CustomerSchemaType) As(alias string) CustomerSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t CustomerSchemaType) ModelType() *Customer {
	return &t.fieldType
}

func (t CustomerSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t CustomerSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.Email,
		t.Phone,
		t.CreatedAt,
	}
}

func (t CustomerSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var CustomerSchema = CustomerSchemaType{
	tableName: "customers",
	ID:        field.NewIntExprField[uint64]("customers", "id", field.FlagPrimaryKey),
	Name:      field.NewTextExprField[string]("customers", "name"),
	Email:     field.NewTextExprField[string]("customers", "email"),
	Phone:     field.NewTextExprField[string]("customers", "phone"),
	CreatedAt: field.NewComparable[time.Time]("customers", "created_at"),
	fieldType: Customer{},
}

// ==================== Order Schema ====================

type OrderSchemaType struct {
	ID         field.IntExprField[uint64]
	CustomerID field.IntExprField[uint64]
	OrderDate  field.Comparable[time.Time]
	TotalPrice field.FloatExprField[float64]
	Status     field.TextExprField[string]
	fieldType  Order
	alias      string
	tableName  string
}

func (t OrderSchemaType) TableName() string {
	return t.tableName
}

func (t OrderSchemaType) Alias() string {
	return t.alias
}

func (t *OrderSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CustomerID = t.CustomerID.WithTable(&tn)
	t.OrderDate = t.OrderDate.WithTable(&tn)
	t.TotalPrice = t.TotalPrice.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
}

func (t OrderSchemaType) As(alias string) OrderSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrderSchemaType) ModelType() *Order {
	return &t.fieldType
}

func (t OrderSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrderSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CustomerID,
		t.OrderDate,
		t.TotalPrice,
		t.Status,
	}
}

func (t OrderSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrderSchema = OrderSchemaType{
	tableName:  "orders",
	ID:         field.NewIntExprField[uint64]("orders", "id", field.FlagPrimaryKey),
	CustomerID: field.NewIntExprField[uint64]("orders", "customer_id", field.FlagIndex),
	OrderDate:  field.NewComparable[time.Time]("orders", "order_date"),
	TotalPrice: field.NewFloatExprField[float64]("orders", "total_price"),
	Status:     field.NewTextExprField[string]("orders", "status"),
	fieldType:  Order{},
}

// ==================== OrderItem Schema ====================

type OrderItemSchemaType struct {
	ID        field.IntExprField[uint64]
	OrderID   field.IntExprField[uint64]
	ProductID field.IntExprField[uint64]
	Quantity  field.IntExprField[int]
	UnitPrice field.FloatExprField[float64]
	fieldType OrderItem
	alias     string
	tableName string
}

func (t OrderItemSchemaType) TableName() string {
	return t.tableName
}

func (t OrderItemSchemaType) Alias() string {
	return t.alias
}

func (t *OrderItemSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.OrderID = t.OrderID.WithTable(&tn)
	t.ProductID = t.ProductID.WithTable(&tn)
	t.Quantity = t.Quantity.WithTable(&tn)
	t.UnitPrice = t.UnitPrice.WithTable(&tn)
}

func (t OrderItemSchemaType) As(alias string) OrderItemSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrderItemSchemaType) ModelType() *OrderItem {
	return &t.fieldType
}

func (t OrderItemSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrderItemSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.OrderID,
		t.ProductID,
		t.Quantity,
		t.UnitPrice,
	}
}

func (t OrderItemSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrderItemSchema = OrderItemSchemaType{
	tableName: "order_items",
	ID:        field.NewIntExprField[uint64]("order_items", "id", field.FlagPrimaryKey),
	OrderID:   field.NewIntExprField[uint64]("order_items", "order_id", field.FlagIndex),
	ProductID: field.NewIntExprField[uint64]("order_items", "product_id", field.FlagIndex),
	Quantity:  field.NewIntExprField[int]("order_items", "quantity"),
	UnitPrice: field.NewFloatExprField[float64]("order_items", "unit_price"),
	fieldType: OrderItem{},
}

// ==================== SalesRecord Schema ====================

type SalesRecordSchemaType struct {
	ID          field.IntExprField[uint64]
	Region      field.TextExprField[string]
	Salesperson field.TextExprField[string]
	Amount      field.FloatExprField[float64]
	SaleDate    field.Comparable[time.Time]
	fieldType   SalesRecord
	alias       string
	tableName   string
}

func (t SalesRecordSchemaType) TableName() string {
	return t.tableName
}

func (t SalesRecordSchemaType) Alias() string {
	return t.alias
}

func (t *SalesRecordSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Region = t.Region.WithTable(&tn)
	t.Salesperson = t.Salesperson.WithTable(&tn)
	t.Amount = t.Amount.WithTable(&tn)
	t.SaleDate = t.SaleDate.WithTable(&tn)
}

func (t SalesRecordSchemaType) As(alias string) SalesRecordSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t SalesRecordSchemaType) ModelType() *SalesRecord {
	return &t.fieldType
}

func (t SalesRecordSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t SalesRecordSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Region,
		t.Salesperson,
		t.Amount,
		t.SaleDate,
	}
}

func (t SalesRecordSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var SalesRecordSchema = SalesRecordSchemaType{
	tableName:   "sales_records",
	ID:          field.NewIntExprField[uint64]("sales_records", "id", field.FlagPrimaryKey),
	Region:      field.NewTextExprField[string]("sales_records", "region", field.FlagIndex),
	Salesperson: field.NewTextExprField[string]("sales_records", "salesperson"),
	Amount:      field.NewFloatExprField[float64]("sales_records", "amount"),
	SaleDate:    field.NewComparable[time.Time]("sales_records", "sale_date", field.FlagIndex),
	fieldType:   SalesRecord{},
}

// ==================== OrgNode Schema ====================

type OrgNodeSchemaType struct {
	ID        field.IntExprField[uint64]
	Name      field.TextExprField[string]
	ParentID  field.IntExprField[*uint64]
	Level     field.IntExprField[int]
	fieldType OrgNode
	alias     string
	tableName string
}

func (t OrgNodeSchemaType) TableName() string {
	return t.tableName
}

func (t OrgNodeSchemaType) Alias() string {
	return t.alias
}

func (t *OrgNodeSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.ParentID = t.ParentID.WithTable(&tn)
	t.Level = t.Level.WithTable(&tn)
}

func (t OrgNodeSchemaType) As(alias string) OrgNodeSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t OrgNodeSchemaType) ModelType() *OrgNode {
	return &t.fieldType
}

func (t OrgNodeSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t OrgNodeSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Name,
		t.ParentID,
		t.Level,
	}
}

func (t OrgNodeSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var OrgNodeSchema = OrgNodeSchemaType{
	tableName: "org_nodes",
	ID:        field.NewIntExprField[uint64]("org_nodes", "id", field.FlagPrimaryKey),
	Name:      field.NewTextExprField[string]("org_nodes", "name"),
	ParentID:  field.NewIntExprField[*uint64]("org_nodes", "parent_id", field.FlagIndex),
	Level:     field.NewIntExprField[int]("org_nodes", "level"),
	fieldType: OrgNode{},
}

// ==================== UserProfile Schema ====================

type UserProfileSchemaType struct {
	ID        field.IntExprField[uint64]
	Username  field.TextExprField[string]
	Profile   field.TextExprField[string]
	fieldType UserProfile
	alias     string
	tableName string
}

func (t UserProfileSchemaType) TableName() string {
	return t.tableName
}

func (t UserProfileSchemaType) Alias() string {
	return t.alias
}

func (t *UserProfileSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.Username = t.Username.WithTable(&tn)
	t.Profile = t.Profile.WithTable(&tn)
}

func (t UserProfileSchemaType) As(alias string) UserProfileSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserProfileSchemaType) ModelType() *UserProfile {
	return &t.fieldType
}

func (t UserProfileSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserProfileSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.Username,
		t.Profile,
	}
}

func (t UserProfileSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserProfileSchema = UserProfileSchemaType{
	tableName: "user_profiles",
	ID:        field.NewIntExprField[uint64]("user_profiles", "id", field.FlagPrimaryKey),
	Username:  field.NewTextExprField[string]("user_profiles", "username"),
	Profile:   field.NewTextExprField[string]("user_profiles", "profile"),
	fieldType: UserProfile{},
}

// ==================== Transaction Schema ====================

type TransactionSchemaType struct {
	ID        field.IntExprField[uint64]
	AccountID field.IntExprField[uint64]
	Amount    field.FloatExprField[float64]
	Type      field.TextExprField[string]
	CreatedAt field.Comparable[time.Time]
	fieldType Transaction
	alias     string
	tableName string
}

func (t TransactionSchemaType) TableName() string {
	return t.tableName
}

func (t TransactionSchemaType) Alias() string {
	return t.alias
}

func (t *TransactionSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.AccountID = t.AccountID.WithTable(&tn)
	t.Amount = t.Amount.WithTable(&tn)
	t.Type = t.Type.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
}

func (t TransactionSchemaType) As(alias string) TransactionSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t TransactionSchemaType) ModelType() *Transaction {
	return &t.fieldType
}

func (t TransactionSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t TransactionSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.AccountID,
		t.Amount,
		t.Type,
		t.CreatedAt,
	}
}

func (t TransactionSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var TransactionSchema = TransactionSchemaType{
	tableName: "transactions",
	ID:        field.NewIntExprField[uint64]("transactions", "id", field.FlagPrimaryKey),
	AccountID: field.NewIntExprField[uint64]("transactions", "account_id", field.FlagIndex),
	Amount:    field.NewFloatExprField[float64]("transactions", "amount"),
	Type:      field.NewTextExprField[string]("transactions", "type"),
	CreatedAt: field.NewComparable[time.Time]("transactions", "created_at"),
	fieldType: Transaction{},
}
