// Code generated by export-types. DO NOT EDIT.
// Source: github.com/donutnomad/gsql/internal/clauses

package gsql

import (
	"github.com/donutnomad/gsql/internal/clauses"
	"github.com/donutnomad/gsql/internal/fields"
)

// ==================== Constructors ====================

// Case 创建搜索式 CASE 表达式构建器
//
// 搜索式 CASE 语法:
//
//	CASE
//	    WHEN condition1 THEN result1
//	    WHEN condition2 THEN result2
//	    [ELSE default_result]
//	END
//
// 用法:
//
//	Case[int, gsql.IntExpr[int]]().
//	    When(user.Age.Gte(18), gsql.IntVal(1)).
//	    When(user.Age.Lt(18), gsql.IntVal(0)).
//	    Else(gsql.IntVal(-1))
func Case[R any, ResultExpr fields.Expressions[R]]() *clauses.SearchCaseBuilder[ResultExpr, R] {
	return clauses.Case[R, ResultExpr]()
}

// CaseValue 创建简单 CASE 表达式构建器（简单 CASE）
// 用法: gsql.CaseValue(target).When(cond1val, val1).When(cond2val, val2).Else(defaultVal)
// CASE expression
// WHEN value1 THEN result1
// WHEN value2 THEN result2
// [ELSE default_result]
// END
func CaseValue[V any, R any, ResultExpr fields.Expressions[R], ValExpr fields.Expressions[V]](expression ValExpr) *clauses.SimpleCaseBuilder[ValExpr, V, ResultExpr, R] {
	return clauses.CaseValue[V, R, ResultExpr, ValExpr](expression)
}

// ==================== Type Aliases ====================

type (
	SearchCaseBuilder[ResultExpr fields.Expressions[R], R any]                                       = clauses.SearchCaseBuilder[ResultExpr, R]
	SimpleCaseBuilder[ValExpr fields.Expressions[V], V any, ResultExpr fields.Expressions[R], R any] = clauses.SimpleCaseBuilder[ValExpr, V, ResultExpr, R]
)

// ==================== Variables ====================

var (
	Cases = clauses.Cases
)
