// Code generated by export-types. DO NOT EDIT.
// Source: github.com/donutnomad/gsql/internal/fields

package gsql

import (
	"github.com/donutnomad/gsql/clause"
	"github.com/donutnomad/gsql/field"
	"github.com/donutnomad/gsql/internal/fields"
)

// ==================== Constructors ====================

func NewDate[T any](expr clause.Expression) fields.Date[T] {
	return fields.NewDate[T](expr)
}

func NewDateField[T any](tableName, name string, flags ...field.FieldFlag) fields.DateField[T] {
	return fields.NewDateField[T](tableName, name, flags...)
}

func NewDateFieldFrom[T any](f field.IField) fields.DateField[T] {
	return fields.NewDateFieldFrom[T](f)
}

func NewDateTime[T any](expr clause.Expression) fields.DateTime[T] {
	return fields.NewDateTime[T](expr)
}

func NewDateTimeField[T any](tableName, name string, flags ...field.FieldFlag) fields.DateTimeField[T] {
	return fields.NewDateTimeField[T](tableName, name, flags...)
}

func NewDateTimeFieldFrom[T any](f field.IField) fields.DateTimeField[T] {
	return fields.NewDateTimeFieldFrom[T](f)
}

func NewDecimal[T any](expr clause.Expression) fields.Decimal[T] {
	return fields.NewDecimal[T](expr)
}

func NewDecimalField[T any](tableName, name string, flags ...field.FieldFlag) fields.DecimalField[T] {
	return fields.NewDecimalField[T](tableName, name, flags...)
}

func NewDecimalFieldFrom[T any](f field.IField) fields.DecimalField[T] {
	return fields.NewDecimalFieldFrom[T](f)
}

func NewFloat[T any](expr clause.Expression) fields.Float[T] {
	return fields.NewFloat[T](expr)
}

func NewFloatField[T any](tableName, name string, flags ...field.FieldFlag) fields.FloatField[T] {
	return fields.NewFloatField[T](tableName, name, flags...)
}

func NewFloatFieldFrom[T any](f field.IField) fields.FloatField[T] {
	return fields.NewFloatFieldFrom[T](f)
}

func NewInt[T any](expr clause.Expression) fields.Int[T] {
	return fields.NewInt[T](expr)
}

func NewIntField[T any](tableName, name string, flags ...field.FieldFlag) fields.IntField[T] {
	return fields.NewIntField[T](tableName, name, flags...)
}

func NewIntFieldFrom[T any](f field.IField) fields.IntField[T] {
	return fields.NewIntFieldFrom[T](f)
}

func NewJson(expr clause.Expression) fields.Json {
	return fields.NewJson(expr)
}

func NewString[T any](expr clause.Expression) fields.String[T] {
	return fields.NewString[T](expr)
}

func NewTextField[T any](tableName, name string, flags ...field.FieldFlag) fields.TextField[T] {
	return fields.NewTextField[T](tableName, name, flags...)
}

func NewTextFieldFrom[T any](f field.IField) fields.TextField[T] {
	return fields.NewTextFieldFrom[T](f)
}

func NewTime[T any](expr clause.Expression) fields.Time[T] {
	return fields.NewTime[T](expr)
}

func NewTimeField[T any](tableName, name string, flags ...field.FieldFlag) fields.TimeField[T] {
	return fields.NewTimeField[T](tableName, name, flags...)
}

func NewTimeFieldFrom[T any](f field.IField) fields.TimeField[T] {
	return fields.NewTimeFieldFrom[T](f)
}

func NewYear[T any](expr clause.Expression) fields.Year[T] {
	return fields.NewYear[T](expr)
}

func BoolColumn(name string) fields.BoolColumnBuilder {
	return fields.BoolColumn(name)
}

func Column[T any](name string) fields.ColumnBuilder[T] {
	return fields.Column[T](name)
}

func FloatColumn(name string) fields.FloatColumnBuilder {
	return fields.FloatColumn(name)
}

func IntColumn(name string) fields.IntColumnBuilder {
	return fields.IntColumn(name)
}

func StringColumn(name string) fields.StringColumnBuilder {
	return fields.StringColumn(name)
}

func TimeColumn(name string) fields.TimeColumnBuilder {
	return fields.TimeColumn(name)
}

// ==================== Type Aliases ====================

type (
	BoolColumnBuilder     = fields.BoolColumnBuilder
	ColumnBuilder[T any]  = fields.ColumnBuilder[T]
	Date[T any]           = fields.Date[T]
	DateColumnBuilder     = fields.DateColumnBuilder
	DateField[T any]      = fields.DateField[T]
	DateTime[T any]       = fields.DateTime[T]
	DateTimeColumnBuilder = fields.DateTimeColumnBuilder
	DateTimeField[T any]  = fields.DateTimeField[T]
	Decimal[T any]        = fields.Decimal[T]
	DecimalColumnBuilder  = fields.DecimalColumnBuilder
	DecimalField[T any]   = fields.DecimalField[T]
	Float[T any]          = fields.Float[T]
	FloatColumnBuilder    = fields.FloatColumnBuilder
	FloatField[T any]     = fields.FloatField[T]
	Int[T any]            = fields.Int[T]
	IntColumnBuilder      = fields.IntColumnBuilder
	IntField[T any]       = fields.IntField[T]
	Json                  = fields.Json
	JsonInput             = fields.JsonInput
	String[T any]         = fields.String[T]
	StringColumnBuilder   = fields.StringColumnBuilder
	TextField[T any]      = fields.TextField[T]
	Time[T any]           = fields.Time[T]
	TimeColumnBuilder     = fields.TimeColumnBuilder
	TimeField[T any]      = fields.TimeField[T]
	Year[T any]           = fields.Year[T]
)
