// Code generated by export-types. DO NOT EDIT.
// Source: github.com/donutnomad/gsql/internal/fields

package gsql

import (
	"github.com/donutnomad/gsql/clause"
	"github.com/donutnomad/gsql/field"
	"github.com/donutnomad/gsql/internal/fields"
)

// ==================== Constructors ====================

func NewDateExpr[T any](expr clause.Expression) fields.DateExpr[T] {
	return fields.NewDateExpr[T](expr)
}

func NewDateExprField[T any](tableName, name string, flags ...field.FieldFlag) fields.DateExprField[T] {
	return fields.NewDateExprField[T](tableName, name, flags...)
}

func NewDateExprFieldFrom[T any](f field.IField) fields.DateExprField[T] {
	return fields.NewDateExprFieldFrom[T](f)
}

func NewDateTimeExpr[T any](expr clause.Expression) fields.DateTimeExpr[T] {
	return fields.NewDateTimeExpr[T](expr)
}

func NewDateTimeExprField[T any](tableName, name string, flags ...field.FieldFlag) fields.DateTimeExprField[T] {
	return fields.NewDateTimeExprField[T](tableName, name, flags...)
}

func NewDateTimeExprFieldFrom[T any](f field.IField) fields.DateTimeExprField[T] {
	return fields.NewDateTimeExprFieldFrom[T](f)
}

func NewDecimalExpr[T any](expr clause.Expression) fields.DecimalExpr[T] {
	return fields.NewDecimalExpr[T](expr)
}

func NewDecimalExprField[T any](tableName, name string, flags ...field.FieldFlag) fields.DecimalExprField[T] {
	return fields.NewDecimalExprField[T](tableName, name, flags...)
}

func NewDecimalExprFieldFrom[T any](f field.IField) fields.DecimalExprField[T] {
	return fields.NewDecimalExprFieldFrom[T](f)
}

func NewFloatExpr[T any](expr clause.Expression) fields.FloatExpr[T] {
	return fields.NewFloatExpr[T](expr)
}

func NewFloatExprField[T any](tableName, name string, flags ...field.FieldFlag) fields.FloatExprField[T] {
	return fields.NewFloatExprField[T](tableName, name, flags...)
}

func NewFloatExprFieldFrom[T any](f field.IField) fields.FloatExprField[T] {
	return fields.NewFloatExprFieldFrom[T](f)
}

func NewIntExpr[T any](expr clause.Expression) fields.IntExpr[T] {
	return fields.NewIntExpr[T](expr)
}

func NewIntExprField[T any](tableName, name string, flags ...field.FieldFlag) fields.IntExprField[T] {
	return fields.NewIntExprField[T](tableName, name, flags...)
}

func NewIntExprFieldFrom[T any](f field.IField) fields.IntExprField[T] {
	return fields.NewIntExprFieldFrom[T](f)
}

func NewJsonExpr(expr clause.Expression) fields.JsonExpr {
	return fields.NewJsonExpr(expr)
}

func NewTextExpr[T any](expr clause.Expression) fields.TextExpr[T] {
	return fields.NewTextExpr[T](expr)
}

func NewTextExprField[T any](tableName, name string, flags ...field.FieldFlag) fields.TextExprField[T] {
	return fields.NewTextExprField[T](tableName, name, flags...)
}

func NewTextExprFieldFrom[T any](f field.IField) fields.TextExprField[T] {
	return fields.NewTextExprFieldFrom[T](f)
}

func NewTimeExpr[T any](expr clause.Expression) fields.TimeExpr[T] {
	return fields.NewTimeExpr[T](expr)
}

func NewYearExpr[T any](expr clause.Expression) fields.YearExpr[T] {
	return fields.NewYearExpr[T](expr)
}

func BoolColumn(name string) fields.BoolColumnBuilder {
	return fields.BoolColumn(name)
}

func Column[T any](name string) fields.ColumnBuilder[T] {
	return fields.Column[T](name)
}

func FloatColumn(name string) fields.FloatColumnBuilder {
	return fields.FloatColumn(name)
}

func IntColumn(name string) fields.IntColumnBuilder {
	return fields.IntColumn(name)
}

func StringColumn(name string) fields.StringColumnBuilder {
	return fields.StringColumn(name)
}

func TimeColumn(name string) fields.TimeColumnBuilder {
	return fields.TimeColumn(name)
}

// ==================== Type Aliases ====================

type (
	BoolColumnBuilder        = fields.BoolColumnBuilder
	ColumnBuilder[T any]     = fields.ColumnBuilder[T]
	DateExpr[T any]          = fields.DateExpr[T]
	DateExprField[T any]     = fields.DateExprField[T]
	DateTimeExpr[T any]      = fields.DateTimeExpr[T]
	DateTimeExprField[T any] = fields.DateTimeExprField[T]
	DecimalExpr[T any]       = fields.DecimalExpr[T]
	DecimalExprField[T any]  = fields.DecimalExprField[T]
	FloatColumnBuilder       = fields.FloatColumnBuilder
	FloatExpr[T any]         = fields.FloatExpr[T]
	FloatExprField[T any]    = fields.FloatExprField[T]
	IntColumnBuilder         = fields.IntColumnBuilder
	IntExpr[T any]           = fields.IntExpr[T]
	IntExprField[T any]      = fields.IntExprField[T]
	JsonExpr                 = fields.JsonExpr
	JsonInput                = fields.JsonInput
	StringColumnBuilder      = fields.StringColumnBuilder
	TextExpr[T any]          = fields.TextExpr[T]
	TextExprField[T any]     = fields.TextExprField[T]
	TimeColumnBuilder        = fields.TimeColumnBuilder
	TimeExpr[T any]          = fields.TimeExpr[T]
	YearExpr[T any]          = fields.YearExpr[T]
)
