// Code generated by gormgen. DO NOT EDIT.
package example2

import (
	"time"

	gsql "github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
	"github.com/shopspring/decimal"
	"gorm.io/gorm"
)

type UserSchemaType struct {
	ID        field.Comparable[uint]
	CreatedAt field.Comparable[time.Time]
	UpdatedAt field.Comparable[time.Time]
	DeletedAt field.Comparable[gorm.DeletedAt]
	Name      field.Pattern[string]
	Age       field.Comparable[int32]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TableName(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.DeletedAt = t.DeletedAt.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Age = t.Age.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.DeletedAt,
		t.Name,
		t.Age,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        field.NewComparable[uint]("users", "id", field.FlagPrimaryKey),
	CreatedAt: field.NewComparable[time.Time]("users", "created_at"),
	UpdatedAt: field.NewComparable[time.Time]("users", "updated_at"),
	DeletedAt: field.NewComparable[gorm.DeletedAt]("users", "deleted_at", field.FlagIndex),
	Name:      field.NewPattern[string]("users", "name", field.FlagUniqueIndex),
	Age:       field.NewComparable[int32]("users", "age"),
	fieldType: User{},
}

type ListingSchemaType struct {
	ID         field.Comparable[uint]
	CreatedAt  field.Comparable[time.Time]
	UpdatedAt  field.Comparable[time.Time]
	DeletedAt  field.Comparable[gorm.DeletedAt]
	BusinessID field.Comparable[uint64]
	UserID     field.Comparable[uint64]
	fieldType  ListingPO
	alias      string
	tableName  string
}

func (t ListingSchemaType) TableName() string {
	return t.tableName
}

func (t ListingSchemaType) Alias() string {
	return t.alias
}

func (t *ListingSchemaType) WithTable(tableName string) {
	tn := gsql.TableName(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.DeletedAt = t.DeletedAt.WithTable(&tn)
	t.BusinessID = t.BusinessID.WithTable(&tn)
	t.UserID = t.UserID.WithTable(&tn)
}

func (t ListingSchemaType) As(alias string) ListingSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t ListingSchemaType) ModelType() *ListingPO {
	return &t.fieldType
}

func (t ListingSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t ListingSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.DeletedAt,
		t.BusinessID,
		t.UserID,
	}
}

func (t ListingSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var ListingSchema = ListingSchemaType{
	tableName:  "listing",
	ID:         field.NewComparable[uint]("listing", "id", field.FlagPrimaryKey),
	CreatedAt:  field.NewComparable[time.Time]("listing", "created_at"),
	UpdatedAt:  field.NewComparable[time.Time]("listing", "updated_at"),
	DeletedAt:  field.NewComparable[gorm.DeletedAt]("listing", "deleted_at", field.FlagIndex),
	BusinessID: field.NewComparable[uint64]("listing", "business_id"),
	UserID:     field.NewComparable[uint64]("listing", "user_id"),
	fieldType:  ListingPO{},
}

type RORRequestSchemaType struct {
	ID                     field.Comparable[uint]
	CreatedAt              field.Comparable[time.Time]
	UpdatedAt              field.Comparable[time.Time]
	NFTContract            field.Pattern[string]
	NFTID                  field.Comparable[int64]
	NFTStatus              field.Comparable[NFTStatus]
	Updated                field.Comparable[bool]
	TokenID                field.Comparable[uint]
	TokenName              field.Pattern[string]
	TokenSymbol            field.Pattern[string]
	TokenDecimals          field.Comparable[uint8]
	Creator                field.Pattern[string]
	From                   field.Pattern[string]
	Amount                 field.Comparable[decimal.Decimal]
	Receiver               field.Pattern[string]
	PartyA                 field.Pattern[string]
	ExecutionDateStartTime field.Comparable[int64]
	ExecutionDateEndTime   field.Comparable[int64]
	ExecutionDateDay       field.Comparable[int32]
	ExecutionDateType      field.Comparable[uint8]
	LogicAnd               field.Comparable[bool]
	Conditions             field.Pattern[string]
	RecordCreatedAt        field.Comparable[int64]
	NFTCreatedAt           field.Comparable[int64]
	Status                 field.Comparable[RORRequestStatus]
	UpdateAtBlockNumber    field.Comparable[uint64]
	UpdateAtBlockTimestamp field.Comparable[int64]
	fieldType              RORRequest
	alias                  string
	tableName              string
}

func (t RORRequestSchemaType) TableName() string {
	return t.tableName
}

func (t RORRequestSchemaType) Alias() string {
	return t.alias
}

func (t *RORRequestSchemaType) WithTable(tableName string) {
	tn := gsql.TableName(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.NFTContract = t.NFTContract.WithTable(&tn)
	t.NFTID = t.NFTID.WithTable(&tn)
	t.NFTStatus = t.NFTStatus.WithTable(&tn)
	t.Updated = t.Updated.WithTable(&tn)
	t.TokenID = t.TokenID.WithTable(&tn)
	t.TokenName = t.TokenName.WithTable(&tn)
	t.TokenSymbol = t.TokenSymbol.WithTable(&tn)
	t.TokenDecimals = t.TokenDecimals.WithTable(&tn)
	t.Creator = t.Creator.WithTable(&tn)
	t.From = t.From.WithTable(&tn)
	t.Amount = t.Amount.WithTable(&tn)
	t.Receiver = t.Receiver.WithTable(&tn)
	t.PartyA = t.PartyA.WithTable(&tn)
	t.ExecutionDateStartTime = t.ExecutionDateStartTime.WithTable(&tn)
	t.ExecutionDateEndTime = t.ExecutionDateEndTime.WithTable(&tn)
	t.ExecutionDateDay = t.ExecutionDateDay.WithTable(&tn)
	t.ExecutionDateType = t.ExecutionDateType.WithTable(&tn)
	t.LogicAnd = t.LogicAnd.WithTable(&tn)
	t.Conditions = t.Conditions.WithTable(&tn)
	t.RecordCreatedAt = t.RecordCreatedAt.WithTable(&tn)
	t.NFTCreatedAt = t.NFTCreatedAt.WithTable(&tn)
	t.Status = t.Status.WithTable(&tn)
	t.UpdateAtBlockNumber = t.UpdateAtBlockNumber.WithTable(&tn)
	t.UpdateAtBlockTimestamp = t.UpdateAtBlockTimestamp.WithTable(&tn)
}

func (t RORRequestSchemaType) As(alias string) RORRequestSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t RORRequestSchemaType) ModelType() *RORRequest {
	return &t.fieldType
}

func (t RORRequestSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t RORRequestSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.NFTContract,
		t.NFTID,
		t.NFTStatus,
		t.Updated,
		t.TokenID,
		t.TokenName,
		t.TokenSymbol,
		t.TokenDecimals,
		t.Creator,
		t.From,
		t.Amount,
		t.Receiver,
		t.PartyA,
		t.ExecutionDateStartTime,
		t.ExecutionDateEndTime,
		t.ExecutionDateDay,
		t.ExecutionDateType,
		t.LogicAnd,
		t.Conditions,
		t.RecordCreatedAt,
		t.NFTCreatedAt,
		t.Status,
		t.UpdateAtBlockNumber,
		t.UpdateAtBlockTimestamp,
	}
}

func (t RORRequestSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var RORRequestSchema = RORRequestSchemaType{
	tableName:              "abt_ror_request",
	ID:                     field.NewComparable[uint]("abt_ror_request", "id", field.FlagPrimaryKey),
	CreatedAt:              field.NewComparable[time.Time]("abt_ror_request", "created_at"),
	UpdatedAt:              field.NewComparable[time.Time]("abt_ror_request", "updated_at"),
	NFTContract:            field.NewPattern[string]("abt_ror_request", "nft_contract"),
	NFTID:                  field.NewComparable[int64]("abt_ror_request", "nft_id", field.FlagIndex),
	NFTStatus:              field.NewComparable[NFTStatus]("abt_ror_request", "nft_status"),
	Updated:                field.NewComparable[bool]("abt_ror_request", "updated"),
	TokenID:                field.NewComparable[uint]("abt_ror_request", "token_id"),
	TokenName:              field.NewPattern[string]("abt_ror_request", "token_name"),
	TokenSymbol:            field.NewPattern[string]("abt_ror_request", "token_symbol"),
	TokenDecimals:          field.NewComparable[uint8]("abt_ror_request", "token_decimals"),
	Creator:                field.NewPattern[string]("abt_ror_request", "creator"),
	From:                   field.NewPattern[string]("abt_ror_request", "from"),
	Amount:                 field.NewComparable[decimal.Decimal]("abt_ror_request", "amount"),
	Receiver:               field.NewPattern[string]("abt_ror_request", "receiver"),
	PartyA:                 field.NewPattern[string]("abt_ror_request", "party_a"),
	ExecutionDateStartTime: field.NewComparable[int64]("abt_ror_request", "execution_date_start_time"),
	ExecutionDateEndTime:   field.NewComparable[int64]("abt_ror_request", "execution_date_end_time"),
	ExecutionDateDay:       field.NewComparable[int32]("abt_ror_request", "execution_date_day"),
	ExecutionDateType:      field.NewComparable[uint8]("abt_ror_request", "execution_date_type"),
	LogicAnd:               field.NewComparable[bool]("abt_ror_request", "logic_and"),
	Conditions:             field.NewPattern[string]("abt_ror_request", "conditions"),
	RecordCreatedAt:        field.NewComparable[int64]("abt_ror_request", "record_created_at"),
	NFTCreatedAt:           field.NewComparable[int64]("abt_ror_request", "nft_created_at"),
	Status:                 field.NewComparable[RORRequestStatus]("abt_ror_request", "status"),
	UpdateAtBlockNumber:    field.NewComparable[uint64]("abt_ror_request", "update_at_block_number"),
	UpdateAtBlockTimestamp: field.NewComparable[int64]("abt_ror_request", "update_at_block_timestamp"),
	fieldType:              RORRequest{},
}

type RORTransferBalanceSchemaType struct {
	ID          field.Comparable[uint]
	CreatedAt   field.Comparable[time.Time]
	UpdatedAt   field.Comparable[time.Time]
	NFTContract field.Pattern[string]
	NFTID       field.Comparable[int64]
	Account     field.Pattern[string]
	Balance     field.Comparable[decimal.Decimal]
	TxHashs     field.Pattern[string]
	fieldType   RORTransferBalance
	alias       string
	tableName   string
}

func (t RORTransferBalanceSchemaType) TableName() string {
	return t.tableName
}

func (t RORTransferBalanceSchemaType) Alias() string {
	return t.alias
}

func (t *RORTransferBalanceSchemaType) WithTable(tableName string) {
	tn := gsql.TableName(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.NFTContract = t.NFTContract.WithTable(&tn)
	t.NFTID = t.NFTID.WithTable(&tn)
	t.Account = t.Account.WithTable(&tn)
	t.Balance = t.Balance.WithTable(&tn)
	t.TxHashs = t.TxHashs.WithTable(&tn)
}

func (t RORTransferBalanceSchemaType) As(alias string) RORTransferBalanceSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t RORTransferBalanceSchemaType) ModelType() *RORTransferBalance {
	return &t.fieldType
}

func (t RORTransferBalanceSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t RORTransferBalanceSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.NFTContract,
		t.NFTID,
		t.Account,
		t.Balance,
		t.TxHashs,
	}
}

func (t RORTransferBalanceSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var RORTransferBalanceSchema = RORTransferBalanceSchemaType{
	tableName:   "abt_ror_transfer",
	ID:          field.NewComparable[uint]("abt_ror_transfer", "id", field.FlagPrimaryKey),
	CreatedAt:   field.NewComparable[time.Time]("abt_ror_transfer", "created_at"),
	UpdatedAt:   field.NewComparable[time.Time]("abt_ror_transfer", "updated_at"),
	NFTContract: field.NewPattern[string]("abt_ror_transfer", "nft_contract", field.FlagIndex),
	NFTID:       field.NewComparable[int64]("abt_ror_transfer", "nft_id", field.FlagIndex),
	Account:     field.NewPattern[string]("abt_ror_transfer", "account", field.FlagIndex),
	Balance:     field.NewComparable[decimal.Decimal]("abt_ror_transfer", "balance"),
	TxHashs:     field.NewPattern[string]("abt_ror_transfer", "tx_hashs"),
	fieldType:   RORTransferBalance{},
}
