// Code generated by gen1.go; DO NOT EDIT.

package fields

// ==================== DateExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e DateExpr[T]) IfNull(defaultValue any) DateExpr[T] {
	return NewDateExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e DateExpr[T]) Coalesce(values ...any) DateExpr[T] {
	return NewDateExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e DateExpr[T]) Nullif(value any) DateExpr[T] {
	return NewDateExpr[T](e.nullifExpr(value))
}

// ==================== DateTimeExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e DateTimeExpr[T]) IfNull(defaultValue any) DateTimeExpr[T] {
	return NewDateTimeExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e DateTimeExpr[T]) Coalesce(values ...any) DateTimeExpr[T] {
	return NewDateTimeExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e DateTimeExpr[T]) Nullif(value any) DateTimeExpr[T] {
	return NewDateTimeExpr[T](e.nullifExpr(value))
}

// ==================== TimeExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e TimeExpr[T]) IfNull(defaultValue any) TimeExpr[T] {
	return NewTimeExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e TimeExpr[T]) Coalesce(values ...any) TimeExpr[T] {
	return NewTimeExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e TimeExpr[T]) Nullif(value any) TimeExpr[T] {
	return NewTimeExpr[T](e.nullifExpr(value))
}

// ==================== TimestampExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e TimestampExpr[T]) IfNull(defaultValue any) TimestampExpr[T] {
	return NewTimestampExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e TimestampExpr[T]) Coalesce(values ...any) TimestampExpr[T] {
	return NewTimestampExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e TimestampExpr[T]) Nullif(value any) TimestampExpr[T] {
	return NewTimestampExpr[T](e.nullifExpr(value))
}

// ==================== YearExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e YearExpr[T]) IfNull(defaultValue any) YearExpr[T] {
	return NewYearExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e YearExpr[T]) Coalesce(values ...any) YearExpr[T] {
	return NewYearExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e YearExpr[T]) Nullif(value any) YearExpr[T] {
	return NewYearExpr[T](e.nullifExpr(value))
}

