// Code generated by gen1.go; DO NOT EDIT.

package fields

// ==================== DecimalExpr 生成的方法 ====================

// Add 加法 (+)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT price + 100 FROM products;
// SELECT users.age + 1 FROM users;
func (e DecimalExpr[T]) Add(value any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.addExpr(value))
}

// Sub 减法 (-)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT price - discount FROM products;
// SELECT stock - sold FROM inventory;
func (e DecimalExpr[T]) Sub(value any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.subExpr(value))
}

// Mul 乘法 (*)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT price * quantity FROM order_items;
// SELECT users.level * 10 as points FROM users;
func (e DecimalExpr[T]) Mul(value any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.mulExpr(value))
}

// Div 除法 (/)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT total / count FROM stats;
// SELECT points / 100 as level FROM users;
func (e DecimalExpr[T]) Div(value any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.divExpr(value))
}

// Neg 取负 (-)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT -price FROM products;
func (e DecimalExpr[T]) Neg() DecimalExpr[T] {
	return NewDecimalExpr[T](e.negExpr())
}

// Mod 取模 (MOD)
// 数据库支持: MySQL (PostgreSQL/SQLite 使用 % 操作符)
// SELECT MOD(10, 3); -- 结果为 1
// SELECT MOD(234, 10); -- 结果为 4
// SELECT * FROM users WHERE MOD(id, 2) = 0; -- 偶数ID
func (e DecimalExpr[T]) Mod(value any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.modExpr(value))
}

// Abs 返回绝对值 (ABS)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT ABS(-10); -- 结果为 10
// SELECT ABS(price - cost) FROM products;
func (e DecimalExpr[T]) Abs() DecimalExpr[T] {
	return NewDecimalExpr[T](e.absExpr())
}

// Round 四舍五入 (ROUND)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT ROUND(1.567); -- 结果为 2
// SELECT ROUND(1.567, 2); -- 结果为 1.57
func (e DecimalExpr[T]) Round(decimals ...int) DecimalExpr[T] {
	return NewDecimalExpr[T](e.roundExpr(decimals...))
}

// Truncate 截断小数 (TRUNCATE)
// 数据库支持: MySQL (PostgreSQL 使用 TRUNC, SQLite 不支持)
// SELECT TRUNCATE(1.567, 2); -- 结果为 1.56
// SELECT TRUNCATE(1.567, 0); -- 结果为 1
func (e DecimalExpr[T]) Truncate(decimals int) DecimalExpr[T] {
	return NewDecimalExpr[T](e.truncateExpr(decimals))
}

func (e DecimalExpr[T]) Pow(exponent float64) DecimalExpr[T] {
	return NewDecimalExpr[T](e.powExpr(exponent))
}

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e DecimalExpr[T]) IfNull(defaultValue any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e DecimalExpr[T]) Coalesce(values ...any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e DecimalExpr[T]) Nullif(value any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.nullifExpr(value))
}

// Greatest 返回参数列表中的最大值 (GREATEST)
// 数据库支持: MySQL, PostgreSQL (SQLite 不支持)
// SELECT GREATEST(10, 20, 30); -- 返回 30
// SELECT GREATEST(price, min_price) FROM products;
func (e DecimalExpr[T]) Greatest(values ...any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.greatestExpr(values...))
}

// Least 返回参数列表中的最小值 (LEAST)
// 数据库支持: MySQL, PostgreSQL (SQLite 不支持)
// SELECT LEAST(10, 20, 30); -- 返回 10
// SELECT LEAST(price, max_price) FROM products;
func (e DecimalExpr[T]) Least(values ...any) DecimalExpr[T] {
	return NewDecimalExpr[T](e.leastExpr(values...))
}

