// Code generated by gen1.go; DO NOT EDIT.

package fields

import (
	"github.com/donutnomad/gsql/clause"
	"github.com/donutnomad/gsql/internal/fieldi"
)

// ==================== JsonExpr 生成的方法 ====================

// Count 计算非NULL值的数量 (COUNT)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT COUNT(id) FROM users;
// SELECT status, COUNT(id) FROM orders GROUP BY status;
func (e JsonExpr[T]) Count() IntExpr[int64] {
	return IntOf[int64](e.countExpr())
}

// CountDistinct 计算不重复非NULL值的数量 (COUNT DISTINCT)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT COUNT(DISTINCT status) FROM orders;
// SELECT user_id, COUNT(DISTINCT product_id) FROM cart GROUP BY user_id;
func (e JsonExpr[T]) CountDistinct() IntExpr[int64] {
	return IntOf[int64](e.countDistinctExpr())
}

// buildExpr 实现 clause.Expression 接口的 Build 方法
func (e JsonExpr[T]) Build(builder clause.Builder) {
	e.buildExpr(builder)
}

// toExprExpr 返回内部的 Expression
func (e JsonExpr[T]) ToExpr() clause.Expression {
	return e.toExprExpr()
}

// asExpr 创建一个别名字段
func (e JsonExpr[T]) As(alias string) fieldi.IField {
	return e.asExpr(alias)
}

// IfNull 如果表达式为NULL则返回默认值
// 内部使用 COALESCE 实现，等价于 Coalesce(defaultValue)
func (e JsonExpr[T]) IfNull(defaultValue any) JsonExpr[T] {
	return JsonOf[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e JsonExpr[T]) Coalesce(values ...any) JsonExpr[T] {
	return JsonOf[T](e.coalesceExpr(values...))
}

// NullIf 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, ") FROM users; -- 空字符串转为NULL
func (e JsonExpr[T]) NullIf(value any) JsonExpr[T] {
	return JsonOf[T](e.nullifExpr(value))
}
