// Code generated by gen1.go; DO NOT EDIT.

package fields

// ==================== TextExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e TextExpr[T]) IfNull(defaultValue any) TextExpr[T] {
	return NewTextExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e TextExpr[T]) Coalesce(values ...any) TextExpr[T] {
	return NewTextExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e TextExpr[T]) Nullif(value any) TextExpr[T] {
	return NewTextExpr[T](e.nullifExpr(value))
}

