// Code generated by gen1.go; DO NOT EDIT.

package fields

import (
	"github.com/donutnomad/gsql/clause"
	"github.com/donutnomad/gsql/internal/fieldi"
)

// ==================== TimeExpr 生成的方法 ====================

// Count 计算非NULL值的数量 (COUNT)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT COUNT(id) FROM users;
// SELECT status, COUNT(id) FROM orders GROUP BY status;
func (e TimeExpr[T]) Count() IntExpr[int64] {
	return IntOf[int64](e.countExpr())
}

// CountDistinct 计算不重复非NULL值的数量 (COUNT DISTINCT)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT COUNT(DISTINCT status) FROM orders;
// SELECT user_id, COUNT(DISTINCT product_id) FROM cart GROUP BY user_id;
func (e TimeExpr[T]) CountDistinct() IntExpr[int64] {
	return IntOf[int64](e.countDistinctExpr())
}

// buildExpr 实现 clause.Expression 接口的 Build 方法
func (e TimeExpr[T]) Build(builder clause.Builder) {
	e.buildExpr(builder)
}

// toExprExpr 返回内部的 Expression
func (e TimeExpr[T]) ToExpr() clause.Expression {
	return e.toExprExpr()
}

// asExpr 创建一个别名字段
func (e TimeExpr[T]) As(alias string) fieldi.IField {
	return e.asExpr(alias)
}

// IfNull 如果表达式为NULL则返回默认值
// 内部使用 COALESCE 实现，等价于 Coalesce(defaultValue)
func (e TimeExpr[T]) IfNull(defaultValue any) TimeExpr[T] {
	return TimeOf[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e TimeExpr[T]) Coalesce(values ...any) TimeExpr[T] {
	return TimeOf[T](e.coalesceExpr(values...))
}

// NullIf 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, ") FROM users; -- 空字符串转为NULL
func (e TimeExpr[T]) NullIf(value any) TimeExpr[T] {
	return TimeOf[T](e.nullifExpr(value))
}

// Avg 计算数值的平均值 (AVG)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT AVG(score) FROM students;
// SELECT class_id, AVG(grade) FROM exams GROUP BY class_id;
func (e TimeExpr[T]) Avg() FloatExpr[float64] {
	return FloatOf[float64](e.avgExpr())
}

// Max 返回最大值 (MAX)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MAX(price) FROM products;
// SELECT category, MAX(stock) FROM inventory GROUP BY category;
func (e TimeExpr[T]) Max() TimeExpr[T] {
	return TimeOf[T](e.maxExpr())
}

// Min 返回最小值 (MIN)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MIN(price) FROM products;
// SELECT category, MIN(stock) FROM inventory GROUP BY category;
func (e TimeExpr[T]) Min() TimeExpr[T] {
	return TimeOf[T](e.minExpr())
}

// Hour 提取小时部分 (HOUR)
// 数据库支持: MySQL, PostgreSQL, SQLite
// 范围: 0-23
func (e TimeExpr[T]) Hour() IntExpr[int] {
	return IntOf[int](e.hourExpr())
}

// Minute 提取分钟部分 (MINUTE)
// 数据库支持: MySQL, PostgreSQL, SQLite
// 范围: 0-59
func (e TimeExpr[T]) Minute() IntExpr[int] {
	return IntOf[int](e.minuteExpr())
}

// Second 提取秒数部分 (SECOND)
// 数据库支持: MySQL, PostgreSQL, SQLite
// 范围: 0-59
func (e TimeExpr[T]) Second() IntExpr[int] {
	return IntOf[int](e.secondExpr())
}

// Microsecond 提取微秒部分 (MICROSECOND)
// 数据库支持: MySQL
// 范围: 0-999999
func (e TimeExpr[T]) Microsecond() IntExpr[int] {
	return IntOf[int](e.microsecondExpr())
}

// TimeToSec 将时间转换为秒数 (TIME_TO_SEC)
// 数据库支持: MySQL
// SELECT TIME_TO_SEC('01:30:00'); -- 返回 5400
func (e TimeExpr[T]) TimeToSec() IntExpr[int] {
	return IntOf[int](e.timeToSecExpr())
}

// AddInterval 在日期/时间上增加时间间隔 (DATE_ADD)
// 数据库支持: MySQL
// interval 格式: "1 DAY", "2 MONTH", "1 YEAR" 等
// 支持单位: MICROSECOND, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR
// SELECT DATE_ADD(date_column, INTERVAL 1 DAY) FROM table;
func (e TimeExpr[T]) AddInterval(interval string) TimeExpr[T] {
	return TimeOf[T](e.addIntervalExpr(interval))
}

// SubInterval 从日期/时间中减去时间间隔 (DATE_SUB)
// 数据库支持: MySQL
// interval 格式: "1 DAY", "2 MONTH", "1 YEAR" 等
// SELECT DATE_SUB(date_column, INTERVAL 1 MONTH) FROM table;
func (e TimeExpr[T]) SubInterval(interval string) TimeExpr[T] {
	return TimeOf[T](e.subIntervalExpr(interval))
}

// TimeDiff 计算与另一个时间的差值 (TIMEDIFF)
// 数据库支持: MySQL
// SELECT TIMEDIFF(end_time, start_time) FROM events;
func (e TimeExpr[T]) TimeDiff(other clause.Expression) TimeExpr[T] {
	return TimeOf[T](e.timeDiffExpr(other))
}

// TimeFormat 格式化时间为字符串 (TIME_FORMAT)
// 数据库支持: MySQL
// SELECT TIME_FORMAT(time_column, '%H:%i:%s') FROM table;
func (e TimeExpr[T]) Format(format string) StringExpr[string] {
	return StringOf[string](e.timeFormatExpr(format))
}
