// Code generated by gen1.go; DO NOT EDIT.

package fields

import (
	"github.com/donutnomad/gsql/clause"
	"github.com/donutnomad/gsql/field"
)

// ==================== TimestampExpr 生成的方法 ====================

// IfNull 如果表达式为NULL则返回默认值 (IFNULL)
// 数据库支持: MySQL, SQLite (PostgreSQL 使用 COALESCE)
// SELECT IFNULL(nickname, 'Anonymous') FROM users;
// 
// Deprecated: 建议使用 Coalesce 替代，以获得更好的跨数据库兼容性
func (e TimestampExpr[T]) IfNull(defaultValue any) TimestampExpr[T] {
	return NewTimestampExpr[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e TimestampExpr[T]) Coalesce(values ...any) TimestampExpr[T] {
	return NewTimestampExpr[T](e.coalesceExpr(values...))
}

// Nullif 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, '') FROM users; -- 空字符串转为NULL
func (e TimestampExpr[T]) Nullif(value any) TimestampExpr[T] {
	return NewTimestampExpr[T](e.nullifExpr(value))
}

// Max 返回最大值 (MAX)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MAX(price) FROM products;
// SELECT category, MAX(stock) FROM inventory GROUP BY category;
func (e TimestampExpr[T]) Max() TimestampExpr[T] {
	return NewTimestampExpr[T](e.maxExpr())
}

// Min 返回最小值 (MIN)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MIN(price) FROM products;
// SELECT category, MIN(stock) FROM inventory GROUP BY category;
func (e TimestampExpr[T]) Min() TimestampExpr[T] {
	return NewTimestampExpr[T](e.minExpr())
}

// Year 提取年份部分 (YEAR)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT YEAR(date_column) FROM table;
func (e TimestampExpr[T]) Year() IntExpr[int] {
	return NewIntExpr[int](e.yearExpr())
}

// Month 提取月份部分 (MONTH)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MONTH(date_column) FROM table;
func (e TimestampExpr[T]) Month() IntExpr[int] {
	return NewIntExpr[int](e.monthExpr())
}

// Day 提取天数部分 (DAY)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT DAY(date_column) FROM table;
func (e TimestampExpr[T]) Day() IntExpr[int] {
	return NewIntExpr[int](e.dayExpr())
}

// DayOfMonth 提取一月中的天数 (DAYOFMONTH)
// 数据库支持: MySQL
// 与 DAY() 等价
func (e TimestampExpr[T]) DayOfMonth() IntExpr[int] {
	return NewIntExpr[int](e.dayOfMonthExpr())
}

// DayOfWeek 返回一周中的索引 (DAYOFWEEK)
// 数据库支持: MySQL
// 1=周日, 2=周一, ..., 7=周六
func (e TimestampExpr[T]) DayOfWeek() IntExpr[int] {
	return NewIntExpr[int](e.dayOfWeekExpr())
}

// DayOfYear 返回一年中的天数 (DAYOFYEAR)
// 数据库支持: MySQL
// 范围: 1-366
func (e TimestampExpr[T]) DayOfYear() IntExpr[int] {
	return NewIntExpr[int](e.dayOfYearExpr())
}

// Week 提取周数 (WEEK)
// 数据库支持: MySQL
// 范围: 0-53
func (e TimestampExpr[T]) Week() IntExpr[int] {
	return NewIntExpr[int](e.weekExpr())
}

// WeekOfYear 提取周数 (WEEKOFYEAR)
// 数据库支持: MySQL
// 范围: 1-53，相当于 WEEK(date, 3)
func (e TimestampExpr[T]) WeekOfYear() IntExpr[int] {
	return NewIntExpr[int](e.weekOfYearExpr())
}

// Quarter 提取季度 (QUARTER)
// 数据库支持: MySQL
// 范围: 1-4
func (e TimestampExpr[T]) Quarter() IntExpr[int] {
	return NewIntExpr[int](e.quarterExpr())
}

// Hour 提取小时部分 (HOUR)
// 数据库支持: MySQL, PostgreSQL, SQLite
// 范围: 0-23
func (e TimestampExpr[T]) Hour() IntExpr[int] {
	return NewIntExpr[int](e.hourExpr())
}

// Minute 提取分钟部分 (MINUTE)
// 数据库支持: MySQL, PostgreSQL, SQLite
// 范围: 0-59
func (e TimestampExpr[T]) Minute() IntExpr[int] {
	return NewIntExpr[int](e.minuteExpr())
}

// Second 提取秒数部分 (SECOND)
// 数据库支持: MySQL, PostgreSQL, SQLite
// 范围: 0-59
func (e TimestampExpr[T]) Second() IntExpr[int] {
	return NewIntExpr[int](e.secondExpr())
}

// Microsecond 提取微秒部分 (MICROSECOND)
// 数据库支持: MySQL
// 范围: 0-999999
func (e TimestampExpr[T]) Microsecond() IntExpr[int] {
	return NewIntExpr[int](e.microsecondExpr())
}

// AddInterval 在日期/时间上增加时间间隔 (DATE_ADD)
// 数据库支持: MySQL
// interval 格式: "1 DAY", "2 MONTH", "1 YEAR" 等
// 支持单位: MICROSECOND, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR
// SELECT DATE_ADD(date_column, INTERVAL 1 DAY) FROM table;
func (e TimestampExpr[T]) AddInterval(interval string) TimestampExpr[T] {
	return NewTimestampExpr[T](e.addIntervalExpr(interval))
}

// SubInterval 从日期/时间中减去时间间隔 (DATE_SUB)
// 数据库支持: MySQL
// interval 格式: "1 DAY", "2 MONTH", "1 YEAR" 等
// SELECT DATE_SUB(date_column, INTERVAL 1 MONTH) FROM table;
func (e TimestampExpr[T]) SubInterval(interval string) TimestampExpr[T] {
	return NewTimestampExpr[T](e.subIntervalExpr(interval))
}

// DateDiff 计算与另一个日期的差值（天数）(DATEDIFF)
// 数据库支持: MySQL
// 返回 this - other 的天数
// SELECT DATEDIFF(end_date, start_date) FROM events;
func (e TimestampExpr[T]) DateDiff(other clause.Expression) IntExpr[int] {
	return NewIntExpr[int](e.dateDiffExpr(other))
}

// TimeDiff 计算与另一个时间的差值 (TIMEDIFF)
// 数据库支持: MySQL
// SELECT TIMEDIFF(end_time, start_time) FROM events;
func (e TimestampExpr[T]) TimeDiff(other clause.Expression) TimeExpr[string] {
	return NewTimeExpr[string](e.timeDiffExpr(other))
}

// TimestampDiff 计算与另一个日期时间的差值（指定单位）(TIMESTAMPDIFF)
// 数据库支持: MySQL
// unit: MICROSECOND, SECOND, MINUTE, HOUR, DAY, WEEK, MONTH, QUARTER, YEAR
// SELECT TIMESTAMPDIFF(DAY, start_date, end_date) FROM events;
func (e TimestampExpr[T]) TimestampDiff(unit string, other clause.Expression) IntExpr[int64] {
	return NewIntExpr[int64](e.timestampDiffExpr(unit, other))
}

// DateFormat 格式化日期为字符串 (DATE_FORMAT)
// 数据库支持: MySQL
// SELECT DATE_FORMAT(date_column, '%Y年%m月%d日') FROM table;
func (e TimestampExpr[T]) Format(format string) TextExpr[string] {
	return NewTextExpr[string](e.dateFormatExpr(format))
}

// Date 提取日期部分 (DATE)
// 数据库支持: MySQL
// SELECT DATE(datetime_column) FROM table;
func (e TimestampExpr[T]) Date() DateExpr[string] {
	return NewDateExpr[string](e.extractDateExpr())
}

// Time 提取时间部分 (TIME)
// 数据库支持: MySQL
// SELECT TIME(datetime_column) FROM table;
func (e TimestampExpr[T]) Time() TimeExpr[string] {
	return NewTimeExpr[string](e.extractTimeExpr())
}

// UnixTimestamp 转换为 Unix 时间戳（秒）(UNIX_TIMESTAMP)
// 数据库支持: MySQL
// SELECT UNIX_TIMESTAMP(date_column) FROM table;
func (e TimestampExpr[T]) UnixTimestamp() IntExpr[int64] {
	return NewIntExpr[int64](e.unixTimestampExpr())
}

// buildExpr 实现 clause.Expression 接口的 Build 方法
func (e TimestampExpr[T]) Build(builder clause.Builder) {
	e.buildExpr(builder)
}

// toExprExpr 返回内部的 Expression
func (e TimestampExpr[T]) ToExpr() clause.Expression {
	return e.toExprExpr()
}

// asExpr 创建一个别名字段
func (e TimestampExpr[T]) As(alias string) field.IField {
	return e.asExpr(alias)
}

