// Code generated by gen1.go; DO NOT EDIT.

package fields

import (
	"github.com/donutnomad/gsql/clause"
	"github.com/donutnomad/gsql/internal/fieldi"
)

// ==================== YearExpr 生成的方法 ====================

// Count 计算非NULL值的数量 (COUNT)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT COUNT(id) FROM users;
// SELECT status, COUNT(id) FROM orders GROUP BY status;
func (e YearExpr[T]) Count() IntExpr[int64] {
	return IntOf[int64](e.countExpr())
}

// CountDistinct 计算不重复非NULL值的数量 (COUNT DISTINCT)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT COUNT(DISTINCT status) FROM orders;
// SELECT user_id, COUNT(DISTINCT product_id) FROM cart GROUP BY user_id;
func (e YearExpr[T]) CountDistinct() IntExpr[int64] {
	return IntOf[int64](e.countDistinctExpr())
}

// buildExpr 实现 clause.Expression 接口的 Build 方法
func (e YearExpr[T]) Build(builder clause.Builder) {
	e.buildExpr(builder)
}

// toExprExpr 返回内部的 Expression
func (e YearExpr[T]) ToExpr() clause.Expression {
	return e.toExprExpr()
}

// asExpr 创建一个别名字段
func (e YearExpr[T]) As(alias string) fieldi.IField {
	return e.asExpr(alias)
}

// IfNull 如果表达式为NULL则返回默认值
// 内部使用 COALESCE 实现，等价于 Coalesce(defaultValue)
func (e YearExpr[T]) IfNull(defaultValue any) YearExpr[T] {
	return YearOf[T](e.ifNullExpr(defaultValue))
}

// Coalesce 返回参数列表中第一个非NULL的值 (COALESCE)
// 数据库支持: MySQL, PostgreSQL, SQLite (SQL 标准函数)
// SELECT COALESCE(nickname, username, 'Anonymous') FROM users;
func (e YearExpr[T]) Coalesce(values ...any) YearExpr[T] {
	return YearOf[T](e.coalesceExpr(values...))
}

// NullIf 如果两个表达式相等则返回NULL，否则返回第一个表达式 (NULLIF)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT NULLIF(username, ") FROM users; -- 空字符串转为NULL
func (e YearExpr[T]) NullIf(value any) YearExpr[T] {
	return YearOf[T](e.nullifExpr(value))
}

// Avg 计算数值的平均值 (AVG)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT AVG(score) FROM students;
// SELECT class_id, AVG(grade) FROM exams GROUP BY class_id;
func (e YearExpr[T]) Avg() FloatExpr[float64] {
	return FloatOf[float64](e.avgExpr())
}

// Max 返回最大值 (MAX)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MAX(price) FROM products;
// SELECT category, MAX(stock) FROM inventory GROUP BY category;
func (e YearExpr[T]) Max() YearExpr[T] {
	return YearOf[T](e.maxExpr())
}

// Min 返回最小值 (MIN)
// 数据库支持: MySQL, PostgreSQL, SQLite
// SELECT MIN(price) FROM products;
// SELECT category, MIN(stock) FROM inventory GROUP BY category;
func (e YearExpr[T]) Min() YearExpr[T] {
	return YearOf[T](e.minExpr())
}

