// Code generated by gogen. DO NOT EDIT.
package example2

import (
	"time"

	"github.com/donutnomad/gsql"
	"github.com/donutnomad/gsql/field"
	"gorm.io/gorm"
)

// ================ gormgen ================

type UserSchemaType struct {
	ID        field.Comparable[uint]
	CreatedAt field.Comparable[time.Time]
	UpdatedAt field.Comparable[time.Time]
	DeletedAt field.Comparable[gorm.DeletedAt]
	Name      field.Pattern[string]
	Age       field.Comparable[int32]
	fieldType User
	alias     string
	tableName string
}

func (t UserSchemaType) TableName() string {
	return t.tableName
}

func (t UserSchemaType) Alias() string {
	return t.alias
}

func (t *UserSchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.DeletedAt = t.DeletedAt.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Age = t.Age.WithTable(&tn)
}

func (t UserSchemaType) As(alias string) UserSchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t UserSchemaType) ModelType() *User {
	return &t.fieldType
}

func (t UserSchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t UserSchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.DeletedAt,
		t.Name,
		t.Age,
	}
}

func (t UserSchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var UserSchema = UserSchemaType{
	tableName: "users",
	ID:        field.NewComparable[uint]("users", "id", field.FlagPrimaryKey),
	CreatedAt: field.NewComparable[time.Time]("users", "created_at"),
	UpdatedAt: field.NewComparable[time.Time]("users", "updated_at"),
	DeletedAt: field.NewComparable[gorm.DeletedAt]("users", "deleted_at", field.FlagIndex),
	Name:      field.NewPattern[string]("users", "name", field.FlagUniqueIndex),
	Age:       field.NewComparable[int32]("users", "age"),
	fieldType: User{},
}

type User2SchemaType struct {
	ID        field.Comparable[uint]
	CreatedAt field.Comparable[time.Time]
	UpdatedAt field.Comparable[time.Time]
	DeletedAt field.Comparable[gorm.DeletedAt]
	Name      field.Pattern[string]
	Age       field.Comparable[int32]
	OrderTime field.Comparable[time.Time]
	fieldType User2
	alias     string
	tableName string
}

func (t User2SchemaType) TableName() string {
	return t.tableName
}

func (t User2SchemaType) Alias() string {
	return t.alias
}

func (t *User2SchemaType) WithTable(tableName string) {
	tn := gsql.TN(tableName)
	t.ID = t.ID.WithTable(&tn)
	t.CreatedAt = t.CreatedAt.WithTable(&tn)
	t.UpdatedAt = t.UpdatedAt.WithTable(&tn)
	t.DeletedAt = t.DeletedAt.WithTable(&tn)
	t.Name = t.Name.WithTable(&tn)
	t.Age = t.Age.WithTable(&tn)
	t.OrderTime = t.OrderTime.WithTable(&tn)
}

func (t User2SchemaType) As(alias string) User2SchemaType {
	var ret = t
	ret.alias = alias
	ret.WithTable(alias)
	return ret
}

func (t User2SchemaType) ModelType() *User2 {
	return &t.fieldType
}

func (t User2SchemaType) ModelTypeAny() any {
	return &t.fieldType
}

func (t User2SchemaType) AllFields() field.BaseFields {
	return field.BaseFields{
		t.ID,
		t.CreatedAt,
		t.UpdatedAt,
		t.DeletedAt,
		t.Name,
		t.Age,
		t.OrderTime,
	}
}

func (t User2SchemaType) Star() field.IField {
	if t.alias != "" {
		return gsql.StarWith(t.alias)
	}
	return gsql.StarWith(t.tableName)
}

var User2Schema = User2SchemaType{
	tableName: "user2s",
	ID:        field.NewComparable[uint]("user2s", "id", field.FlagPrimaryKey),
	CreatedAt: field.NewComparable[time.Time]("user2s", "created_at"),
	UpdatedAt: field.NewComparable[time.Time]("user2s", "updated_at"),
	DeletedAt: field.NewComparable[gorm.DeletedAt]("user2s", "deleted_at", field.FlagIndex),
	Name:      field.NewPattern[string]("user2s", "name", field.FlagUniqueIndex),
	Age:       field.NewComparable[int32]("user2s", "age"),
	OrderTime: field.NewComparable[time.Time]("user2s", "order_time"),
	fieldType: User2{},
}
